title: # a name for your Learning Lab course
tagline: # a short description for your Learning Lab course, displayed on the course catalog
description: # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name:     GYoung
  repo:     GLearners

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: respond
  with: 01_first-response.md
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
# Step 1: Click on the Markdown web-link.
- title: # the title of the step, shown to the learner in the course progress page
  description: # a description of the step, shown to the learner in the course progress page
  event: GLearners will have access the learning lab of the Markdown web-link and learn the tools for the course.
  actions: # a list of the actions that will occur when the step is triggered by an event
  - type: gate
    left: '%payload.pull_request.base.ref%'
    operator: ===
    right: main
    else:
    - type: respond
      with: 01_try-again.md
- type: respond
  with: 01_nice-work.md

# Step 2: EDIT HERE -INTERNAL COMMENT FOR STEP 2
# - title: # the title of the step, shown to the learner in the course progress page
#  description: The learner will be able to know what a Markdown is and the things needed to be successful using Markdown. By the end of the course, the learner should have the basic information and skills to work with Markdown.
#  event: GLearners will learn how to make internal comment for this step.
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 3: Read the description carefully and review a few times if necessary.
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: GLearners will learn how to read description for this lab and apply it.
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 4: Start applying what have learned in the previous lesson.
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: GLearners will apply and demonstrate how much they learned from previous lesson.
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

# Step 5: Check and review before submit work.
# - title: # the title of the step, shown to the learner in the course progress page
#  description: # a description of the step, shown to the learner in the course progress page
#  event: Check and review carefully before finally submitting your assignment.
#  actions: # a list of the actions that will occur when the step is triggered by an event
#  - type: # the type of action, full list at https://lab.github.com/docs/actions

